### ISSUE TITLE
Mashroom Portal Remote App Kubernetes Background Job does not refresh

### ISSUE THREAD

**Issue by cakriwut** [nonblocking/microfrontend-platform-kubernetes#10]
Issue:
Mashroom Portal Remote App Kubernetes Background Job does not refresh the v=<token>

Expected:
The background job will update the refresh token at regular interval. So that it reflect the latest changes.

Step to reproduce:
1. Publish remote app without index.js. (Basically, assume that the remote app publisher only publish mashroom.json and package.json).
2. Fix the remote app, to include index.js and other dist/* resources
3. In the Portal, click Add App

Observation:
1.  Although after fixing the remote app (step reproduce #2) , the Portal is still using the old v=<token>.  example - */___/apps/App/index.js?v=25242424. This results 404 due to the fact that initially this file was not published by the remote app.
2. Accessing the */___/apps/App/index.js - return 200 and the JS file is available.

Hence the problem is the refresh token , was not updated.

Any clue how to force refresh this token?

Thanks.

**Comment by nonblocking** [comment]
Hmm, thats weird, because the the query parameter with the token is actually just for cache busting and doesn't change the way Mashroom looks up the resource at the Remote App server. So, maybe it's just caching issue? Can you try this with disabled browser caching?

**Comment by cakriwut** [comment]
Disabling browser caching doesnt resolve the issue.

Here the interesting part, I remove the service from K8s. Wait for sometimes till the Remote App registration disappear. Then I add the service back. Adding the remote app to the portal and refresh the browser after this step resolve the problem.

**Comment by nonblocking** [comment]
I tried to reproduce the problem but had no luck. But as I said, the version token will be ignored, so if you request */___/apps/App/index.js?v=25242424 the Portal basically just request <your-kubernetes-services>/index.js - and if /index.js is actually there it will be returned, otherwise there should be an error in the Portal log.

**Comment by nonblocking** [comment]
Setup improved in the latest demo version: Now very build creates a new package version wich in turn leads to a new ?v=xxx query which busts the browser cache.
