### ISSUE TITLE
Manually deployed to AWS EKS, service discovery not working, tools for debugging

### ISSUE THREAD

**Issue by devexter** [nonblocking/microfrontend-platform-kubernetes#11]
I have deployed mashroom Portal to AWS EKS k8s cluster.

The portal appears to function correctly

I have configured the remote portal scanner

`        "Mashroom Portal Remote App Kubernetes Background Job": {
          "refreshIntervalSec": 60,
          "k8sNamespacesLabelSelector": ["microfrontends=true"],
          "k8sNamespaces": [],
          "serviceNameFilter": "microfrontend-.*"
        }`

I have setup the serviceaccount, ClusterRole and RoleBinding

I validated the setup with the following commands:

kubectl -n mashroom auth can-i list services --as=system:serviceaccount:mashroom:mashroom-portal
yes

kubectl -n mashroom auth can-i list services --as=system:serviceaccount:mashroom:mashroom-portal
yes

I have deployed the microfrontenddemo1 with the namespace and service labels that match the config 

In the mashroom logs (level: ALL) I see:

[2024-07-01T12:41:00.003] [INFO] mashroom.backgroundJobs.service - Executing background job Mashroom Portal Remote App Background Job
[2024-07-01T12:41:00.003] [INFO] mashroom.portal.remoteAppRegistry - Start processing remote Portal App endpoints
[2024-07-01T12:41:00.003] [INFO] mashroom.portal.remoteAppRegistry - Processed 0 endpoints in 0ms
[2024-07-01T12:41:00.004] [INFO] mashroom.backgroundJobs.service - Background job Mashroom Portal Remote App Background Job completed after 1ms

The remote App does not appear in the portal

Do you have any recommendation for identifying the point in the scan that is failing, e.g. servicerole permissions, namespace label match or service label match?

**Comment by nonblocking** [comment]
Well, I can assure you the service discovery works, since we use it in a bunch of K8S based platform. 

And since I cannot check your K8S setup, I cannot really say much here. But the serviceNameFilter seems not to match. If you want to select the Microfrontend service by label you have to use k8sServiceLabelSelector.

Also, check the Admin UI, it will tell you if at least the namespace selection works.

**Comment by devexter** [comment]
> Well, I can assure you the service discovery works, since we use it in a bunch of K8S based platforms.

100% I know the issue is with my deployment, my experience so far is that this is a great product and I had it working just fine in k3d with the demo scripts.

> And since I cannot check your K8S setup, I cannot really say much here. But the serviceNameFilter seems not to match. If you want to select the Microfrontend service by label you have to use k8sServiceLabelSelector.
> 
> Also, check the Admin UI, it will tell you if at least the namespace selection works.

Thanks for this suggestion it moved me forward a long way as I was not seeing the namespaces listed in the UI.

It turns out I had gotten confused with the log messages, the ones I posted were not from the k8s background job but the plain remote app background job.

I can now see that the k8s scanner job never starts (based on missing log messages), so that is where I am focused now.

I am using a custom config folder, not the bundled development or production config. I'm going to revert to those default configs and see if the scanner starts in those. If it does it looks like it is a config issue on my side.

**Comment by nonblocking** [comment]
The scanner should start in any case, if you have @mashroom/mashroom-portal-remote-app-registry-k8s bundle (in your dependencies) - checkout the Admin UI if the plugin is even there.

**Comment by devexter** [comment]
I think I'm beginning to see where I went wrong.

I based my custom config on the development mashroom.json

When reviewing the k3d demo deployment I can see the environment is set to production.

When I do the same on my EKS cluster then the k8s scanner background job is started instead of the non k8s remote scanner.

I'm still not clear what the config difference is between development/production that causes this change in behavior.

Now I can see the scanner running but it does not match any namespaces, looking at that next.

**Comment by devexter** [comment]
The difference in behavior is caused by the ignorePlugins sections in the mashroom config files.

**Comment by devexter** [comment]
All working now that I have updated the ignorePlugins in my custom config

Thanks for pointing me in the right direction.
